### ISSUE TITLE
pacman doesn't compat with https://dl.bintray.com/git-for-windows/pacman/msys2/$arch/

### ISSUE THREAD

**Issue by lygstate** [Alexpux/MSYS2-packages#210] opened 2015-04-07 15:11 UTC
Server = https://dl.bintray.com/git-for-windows/pacman/msys2/$arch/

```
:: Synchronizing package databases...
 git-for-windows                                                                                  0.0   B  0.00B/s 00:00 [------------------------------------------------------------------------]   0%
 git-for-windows                                                                               1872.0   B   914K/s 00:00 [########################################################################] 100%

error: could not open file /var/lib/pacman/sync/1cb4ed32f5db94fc7c0f9ffa6b315f92fe2d50e3?response-content-disposition=attachment%3Bfilename%3D%22git-for-windows.db%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZX
NvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMWNiNGVkMzJmNWRiOTRmYzdjMGY5ZmZhNmIzMTVmOTJmZTJkNTBlMz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdpdC1mb3
Itd2luZG93cy5kYiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQyODQxOTE5NX0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=Dnkpi2dSSS5ZZYf-bQA143~aYDAPFrU
UrNnuWX7qCam72CCwfL2VT86JzQA8F8GaLtGz5pv-mvsS~8lV0UFjEqBHfSEiW-~vEwP9YcuKCtx5OmdYP9g0H5P4Qc5XXYdZuWP8rY2xCYwe2v3aUrpS0Nk9eRKbYXf0f9rc1YQj6MzqW4ab5T1yUEJbDWXJiNpBEHPElGD-McTtufFSU~3y5czbNJOg3mK8v6wZFTf
Iz2WM-anWrcikR0~IsWmg~aEsznMDKZ9XukCkKoa-d-SHWZZHljuFQPjQFK~dSe09JTV1zssZWPN~DmrYZCCGgnsOcFuUKkw3ls06n4EPceIvgA__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ.sig.part: File name too long
 mingw32                                                                                          0.0   B  0.00B/s 00:00 [------------------------------------------------------------------------]   0%

```

**Comment by Alexpux** [comment] 2015-04-07 15:15
This is your own repo. Why it is my problem?

**Comment by lygstate** [comment] 2015-04-07 15:57
it's bintray.com not a private repository

**Comment by Alexpux** [comment] 2015-04-07 16:03
I mean this is not our official repository. Looking at the error message I can told you only that maybe you don't have signature files for packages/repo databases - ".sig" files.

**Comment by elieux** [comment] 2015-04-07 23:40
@lygstate, what's your repository name? The `Server` URL is not enough to make the final DB URL.

**Comment by lygstate** [comment] 2015-04-08 06:16
`
Server=https://dl.bintray.com/git-for-windows/pacman/msys2/x86_64
`

**Comment by lygstate** [comment] 2015-04-08 06:17
The db link is 
https://dl.bintray.com/git-for-windows/pacman/x86_64/#git-for-windows.db

**Comment by elieux** [comment] 2015-04-08 09:38
I was asking for the name of your repository, as written in `pacman.conf` inside the brackets, but I don't need it anymore because it's written in your first post.

Anyway, I tried downloading from the URL and it isn't a pacman DB file, it's just a HTML file. Pacman package databases are binary files created by the `repo-add` tool.

As for the "file name too long" problem, it _may_ go away once your URL resolves to a file download (rather than HTML page display). Post your progress.

**Comment by lygstate** [comment] 2015-04-08 09:42
@elieux  The url should be https://dl.bintray.com/git-for-windows/pacman/x86_64/git-for-windows.db

**Comment by elieux** [comment] 2015-04-08 09:50
Okay. Have you tried with pacman on Arch Linux?

**Comment by lygstate** [comment] 2015-04-08 09:52
mmmm, it's just for windows.

**Comment by elieux** [comment] 2015-04-08 11:08
If you're talking about the contents of the packages, then it doesn't matter. I'm trying to find out if the problem is specific to MSYS2, or if pacman just doesn't like this URL in general.

Either way, I'm not sure if your use case is supported. I'm getting wildly varying results depending on the command I use to download the DB (certificate problems with `curl -L`, infinite loops with `wget`...). It took a lot of experimenting, but I think I've come up with a work-around for you:

```
XferCommand = /usr/bin/curl -L -k -C - %u > %o

...

[git-for-windows]
Server = https://dl.bintray.com/git-for-windows/pacman/$arch/
SigLevel = Never
```

**Comment by dscho** [comment] 2015-04-08 14:00
I am truly sorry that this has been reported without an appropriate analysis of the problem. It seems that when `pacman` tries to obtain the signature file (which does not exist), it gets redirected, but does not realize that the end result is "this file does not exist". The question is whether 404 is unhandled by `pacman` or whether bintray does not report the correct exit status, but that should have been researched before opening this issue.

**Comment by Alexpux** [comment] 2015-04-08 18:58
@dscho, I see you told that DB link is 
````https://dl.bintray.com/git-for-windows/pacman/x86_64/git-for-windows.db````
But pacman as I remember download by default compressed files ````git-for-windows.db.tar.gz````
Do you have it? Also do you have sign your database with GPG key?

**Comment by dscho** [comment] 2015-04-08 19:46
@Alexpux please note that your comment is seriously borked. The link, for example, does not show up at all. I guess you meant to use Markdown but then used some different markup?

As to your question, yes, we upload both `git-for-windows.db` *and* `git-for-windows.db.tar.xz`: http://dl.bintray.com/git-for-windows/pacman/x86_64/

I have not signed the database nor the packages yet.

**Comment by Alexpux** [comment] 2015-04-08 20:12
Fix comment.

**Comment by elieux** [comment] 2015-04-08 22:44
AFAIK pacman will try URL `<server-url>/<name-of-repository>.db` and it's the server's responsibility to serve something meaningful, mostly by having a symlink to `<name-of-repository>.db.tar.xz`.

OP, did the settings work for you?

**Comment by dscho** [comment] 2015-04-09 05:58
> pacman will try URL <server-url>/<name-of-repository>.db and it's the server's responsibility to serve something meaningful

That is actually found, we upload *both* the `.db` and the `.db.tar.xz` file for that reason. Symbolic links are unfortunately out of the question, we do not own the filespace on Bintray, we just have an API to upload packages via curl.

My guess is that the problem actually arises when the signature is being fetched (and is not found instead), judging by the `.sig.part` suffix.

**Comment by lygstate** [comment] 2015-04-09 08:06
@dscho, so we need to upload `<server-url>/<name-of-repository>.db.sig` to the `Bintray` too, or pacman error will arise, even though it won't affect succeeding procedure by most time.

**Comment by elieux** [comment] 2015-04-09 09:22
Or set `SigLevel = Never` in the repository section in your `pacman.conf`. :)

If you want to start signing, you can look up how on the ArchWiki. I also wrote a short guide that may help: https://sourceforge.net/p/msys2/wiki/Signing%20package%20repositories/

**Comment by dscho** [comment] 2015-04-09 09:52
@elieux thanks, I will look into that as soon as I get back from Git Merge.

**Comment by dscho** [comment] 2015-04-09 09:56
> @dscho, so we need to upload <server-url>/<name-of-repository>.db.sig to the Bintray too

So what makes you say that? Have you any evidence to back up that claim? Or do *I* have to do all the research and all the testing myself, again?

**Comment by nalla** [comment] 2015-04-13 10:06
> @dscho, so we need to upload /.db.sig to the Bintray too

The linked [analysis](https://github.com/git-for-windows/git/issues/76#issuecomment-92298144) implies, if indeed sound, that just uploading the `.sig` file is not enough.

**Comment by elieux** [comment] 2015-04-13 19:47
Oh yeah, I remember that -- it's a somewhat recent change. I've submitted a patch to pacman ML for review. If the patch goes through, pacman should be able to deal with such redirects.

**Comment by nalla** [comment] 2015-04-14 05:00
@elieux do you mean [this](https://lists.archlinux.org/pipermail/pacman-dev/2015-April/020070.html) patch? @dscho maybe we should then give that patch a try first before trying it [ourselfs](https://github.com/Alexpux/MSYS2-pacman/compare/master...dscho:bogus-redirect)?

**Comment by dscho** [comment] 2015-04-14 07:03
@elieux @Alexpux The patch appears to work alright! And @nalla already opened [a PR](https://github.com/git-for-windows/MSYS2-packages/pull/14) to our fork. However, I would be delighted if you would want to merge this into `MSYS2-pacman` proper right away... Would you be interested?

**Comment by elieux** [comment] 2015-04-14 13:18
Yes, that's the one. I'm inclined to having the patch merged into our pacman fork, but @Alexpux has the final vote (and push access).

**Comment by elieux** [comment] 2015-04-14 13:20
By the way, is it possible to meet you GfW people somewhere on IRC?

**Comment by dscho** [comment] 2015-04-14 14:07
@elieux I only rarely go on IRC these days, but sometimes you will find me in https://gitter.im/git-for-windows/git...

**Comment by dscho** [comment] 2015-04-14 14:08
> I'm inclined to having the patch merged into our pacman fork, but @Alexpux has the final vote (and push access).

Great! I have removed our pacman fork from our Pacman repository a while ago and would like to keep it that way.

**Comment by dscho** [comment] 2015-04-15 18:53
@Alexpux please have a look at https://github.com/Alexpux/MSYS2-packages/pull/217. Thanks!

**Comment by elieux** [comment] 2015-04-22 22:11
Status: patch added to our `PKGBUILD`, new package uploaded. Pacman upstream hasn't merged yet.

Can this issue be closed?

**Comment by dscho** [comment] 2015-04-23 06:59
From my point of view: yes, it can be closed.

**Comment by sschuberth** [comment] 2015-04-23 08:10
Our CI also agrees that the issue is fixed: There is no more `error: could not open file` after `downloading git-for-windows.db...` in [here](https://dscho.cloudapp.net/job/gfw-msys2-test-sdk-installer/21/console) compared to [here](https://dscho.cloudapp.net/job/gfw-msys2-test-sdk-installer/17/console).

**Closed** 2015-04-23 11:16 UTC

**Comment by elieux** [comment] 2015-04-23 11:17
I also noticed this in your log:
```
07:34:19 downloading msys.db...
07:34:19 downloading msys.db...
07:34:19 downloading msys.db...
07:34:19 downloading msys.db...
07:34:20 downloading msys.db.sig...
07:34:20 downloading msys.db.sig...
07:34:20 downloading msys.db.sig...
07:34:20 downloading msys.db.sig...
07:34:20 downloading msys.db.sig...
```
I have a patch for this, too. (But I'm less sure of its correctness.) :)
