### ISSUE TITLE
svn

### ISSUE THREAD

**Issue by adepumeena** [Alexpux/MSYS2-packages#1033] opened 2017-10-14 05:00 UTC
Problem occurred when installing svn on Ubuntu 16.04.

After installing the apache2 server and Creation of repository, after that I got this error while connecting to repository by the following command:

sudo svn co file:///svn/repository/

svn: E170013: Unable to connect to a repository at URL 'file:///svn/repository'
svn: E180001: Unable to open repository 'file:///svn/repository'
please help me on this issue.

Thanks in Advance, Meena.

**Comment by mati865** [comment] 2017-10-14 09:57
How is it related to MSYS2?

**Comment by ErichDonGubler** [comment] 2017-11-06 03:32
You seem to have filed two issues for this problem -- could we get one closed, so we can keep the thread in one place?

**Comment by lazka** [comment] 2018-01-25 08:53
Duplicate of #1034

**Closed by lazka** 2018-01-25 08:53 UTC
