### ISSUE TITLE
OpenSSL in MSYS2 is significantly slow

### ISSUE THREAD

**Issue by Jimmy-Z** [Alexpux/MSYS2-packages#983] opened 2017-08-27 05:13 UTC
Seems like it's missing a lot of compiler flags.

````
$ openssl speed -evp aes-128-ecb
Doing aes-128-ecb for 3s on 16 size blocks: 35735957 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 64 size blocks: 9602930 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 256 size blocks: 2424013 aes-128-ecb's in 2.97s
Doing aes-128-ecb for 3s on 1024 size blocks: 608856 aes-128-ecb's in 2.97s
Doing aes-128-ecb for 3s on 8192 size blocks: 76950 aes-128-ecb's in 3.00s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) aes(partial) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -D_WINDLL -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS  -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIOS -DL_ENDIAN -O3 -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-ecb     190591.77k   204862.51k   209079.29k   209992.77k   210124.80k
````

while in mingw
```
$ openssl speed -evp aes-128-ecb
Doing aes-128-ecb for 3s on 16 size blocks: 96248108 aes-128-ecb's in 2.97s
Doing aes-128-ecb for 3s on 64 size blocks: 75987695 aes-128-ecb's in 2.98s
Doing aes-128-ecb for 3s on 256 size blocks: 34411894 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 1024 size blocks: 9570732 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 8192 size blocks: OpenSSL 1.0.2l  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(idx,cisc,2,long) aes(partial) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include -I/mingw64/include -D_WINDLL -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-ecb     518726.65k  1629558.11k  2936481.62k  3266809.86k  3336459.61k
1221848 aes-128-ecb's in 3.00s
````

15x difference on a same machine.

**Comment by irakhlin** [comment] 2017-09-04 15:10
MINGW64:

openssl speed -evp aes-128-ecb
Doing aes-128-ecb for 3s on 16 size blocks: 134851223 aes-128-ecb's in 2.98s
Doing aes-128-ecb for 3s on 64 size blocks: 129724863 aes-128-ecb's in 2.98s
Doing aes-128-ecb for 3s on 256 size blocks: 55209566 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 1024 size blocks: 15364391 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 8192 size blocks: OpenSSL 1.0.2l  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(idx,cisc,2,long) aes(partial) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include -I/mingw64/include -D_WINDLL -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-ecb     722972.00k  2781953.08k  4711216.30k  5244378.79k  5367155.37k
1965511 aes-128-ecb's in 3.00s

MSYS2
Doing aes-128-ecb for 3s on 16 size blocks: 135201870 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 64 size blocks: 130889493 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 256 size blocks: 56107053 aes-128-ecb's in 2.97s
Doing aes-128-ecb for 3s on 1024 size blocks: 15163062 aes-128-ecb's in 3.00s
Doing aes-128-ecb for 3s on 8192 size blocks: 1960251 aes-128-ecb's in 3.00s
OpenSSL 1.0.2l  25 May 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(idx,cisc,16,int) aes(partial) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -D_WINDLL -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS  -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIOS -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-ecb     721076.64k  2792309.18k  4839422.36k  5175658.50k  5352792.06k


Now I did rebuild my msys openssl with version 1.0.2l but i think the major cause of the speed you may be seeing is that I rebuild it and removed no-asm.. When  building it with no-asm I see the same but I would imagine this is the expected result and more to do with package.

**Comment by Jimmy-Z** [comment] 2017-09-28 18:27
I see the package in the repo updated to 1.0.1l, but it still comes with no-asm, why?

**Comment by mingwandroid** [comment] 2017-09-28 20:41
Because you haven't submitted a PR to fix it? This is open source, that's how it works.

**Comment by irakhlin** [comment] 2017-09-29 00:23
Yes, sorry I had only initially responded to the question after doing a few tests to determine the cause and it did not seem like a bug specifically. Its a very easy change to make so Id be more than happy to submit it in a bit.

**Comment by Jimmy-Z** [comment] 2017-09-29 06:57
A single line removal must be done with a PR? Why I've never heard this rule before?

**Comment by irakhlin** [comment] 2017-09-29 07:03
I cant answer that question with any authority but I would guess that its for testing. When a pull request is submitted here the package is build and tests are run in CI. It can suck if you make a single line change and break a package with lots and lots of dependencies causing a chain reaction. 

Regardless, I have made the change and submitted it. Seems it was already merged.
https://github.com/Alexpux/MSYS2-packages/pull/1017

**Comment by mingwandroid** [comment] 2017-09-29 10:58
@Jimmy-Z, We are a community project, rather than expecting others to do work for you, you should join in.

**Comment by Jimmy-Z** [comment] 2017-09-29 11:33
I think "find the problem, identify the problem" is also valuable work, firing a issue is also collaborating, not just ritualized PR.

I don't mean to discredit irakhlin.

**Comment by ErichDonGubler** [comment] 2017-11-07 19:04
@Jimmy-Z: Hey there! Noticed that this issue had some discussion, but I can't see any action items (probably because I'm not too familiar with the issue here). Is there anything left on this issue you'd like to discuss before it gets closed? :) Has you problem actually been resolved to your satisfaction?

**Closed** 2017-11-08 07:26 UTC
