### ISSUE TITLE
libxml2 problem

### ISSUE THREAD

**Issue by jeroenooms** [Alexpux/MSYS2-packages#171] opened 2015-02-20 00:19 UTC
I created the `libxml2.a` static library from the latest recipe, however upon linking to my application I get this error:

```
xml2_doc.o:xml2_doc.cpp:(.text+0x82c): undefined reference to `__imp_xmlFree'
xml2_doc.o:xml2_doc.cpp:(.text+0x914): undefined reference to `__imp_xmlFree'
```

Google suggests that this [comment](https://github.com/GNOME/libxml2/blob/master/include/libxml/xmlexports.h#L111-L115) in `xmlexports.h` might be relevant:

> if defined(IN_LIBXML) this raises problems on mingw with msys
> _imp__xmlFree listed as missing. Try to workaround the problem
>  by also making that declaration when compiling client code.

It seems like the workaround is not working for msys2.

**Comment by mingwandroid** [comment] 2015-02-20 00:32
I will investigate this tomorrow, but the problem is to do with the compilation of the consumer of the static library rather than the library itself.. Probably.

**Comment by jeroenooms** [comment] 2015-02-20 00:36
You are right, I fixed the problem by passing `-DIN_LIBXML` to my `CXXFLAGS` in my client.

**Comment by maoueh** [comment] 2015-02-24 18:16
@jeroenooms Since this is resolved, can you close the issue.

**Closed** 2015-02-24 18:21 UTC
